module.exports = [
  {
    FirstName: "Latrell",
    LastName: "Sprewell",
    Position: "Small Forward",
    Age: 27,
    Height: 6.5,
    Weight: 210,
    College: "UCLA",
    Salary: 4767000,
    Stamina: 87,
    Speed: 93,
    Strength: 91,
    Injured: false
  },
  {
    FirstName: "Shaq",
    LastName: "O'Neil",
    Position: "Center",
    Age: 32,
    Height: 7.1,
    Weight: 300,
    College: "Arizona",
    Salary: 5345000,
    Stamina: 70,
    Speed: 75,
    Strength: 99,
    Injured: false
  },
  {
    FirstName: "Gary",
    LastName: "Payton",
    Position: "Point Guard",
    Age: 34,
    Height: 6.0,
    Weight: 180,
    College: "Gonzaga",
    Salary: 3560000,
    Stamina: 93,
    Speed: 95,
    Strength: 75,
    Injured: false
  },
  {
    FirstName: "Michael",
    LastName: "Jordan",
    Position: "Shooting Guard",
    Age: 34,
    Height: 6.6,
    Weight: 220,
    College: "NY",
    Salary: 6367000,
    Stamina: 97,
    Speed: 97,
    Strength: 88,
    Injured: false
  },
  {
    FirstName: "Tim",
    LastName: "Duncan",
    Position: "Power Forward",
    Age: 33,
    Height: 7.0,
    Weight: 280,
    College: "Texas",
    Salary: 3836000,
    Stamina: 80,
    Speed: 80,
    Strength: 97,
    Injured: false
  }
];
