module.exports = [
  {
    FirstName: "Kevin",
    LastName: "Garnett",
    Position: "Small Forward",
    Age: 28,
    Height: 6.9,
    Weight: 240,
    College: "Mississippi",
    Salary: 3456000,
    Stamina: 85,
    Speed: 87,
    Strength: 93,
    Injured: false,
    BelongsToTeam: "Heat",
    Playing: true
  },
  {
    FirstName: "Alonzo",
    LastName: "Mourning",
    Position: "Center",
    Age: 34,
    Height: 7.0,
    Weight: 300,
    College: "San Diego",
    Salary: 5123000,
    Stamina: 75,
    Speed: 77,
    Strength: 99,
    Injured: false,
    BelongsToTeam: "Heat",
    Playing: true
  },
  {
    FirstName: "John",
    LastName: "Stockton",
    Position: "Point Guard",
    Age: 35,
    Height: 6.0,
    Weight: 180,
    College: "Gonzaga",
    Salary: 4560000,
    Stamina: 95,
    Speed: 97,
    Strength: 70,
    Injured: false,
    BelongsToTeam: "Heat",
    Playing: true
  },
  {
    FirstName: "Kobe",
    LastName: "Bryant",
    Position: "Shooting Guard",
    Age: 27,
    Height: 6.7,
    Weight: 220,
    College: "Italy",
    Salary: 6100000,
    Stamina: 96,
    Speed: 96,
    Strength: 87,
    Injured: false,
    BelongsToTeam: "Heat",
    Playing: true
  },
  {
    FirstName: "Chris",
    LastName: "Webber",
    Position: "Power Forward",
    Age: 31,
    Height: 6.9,
    Weight: 270,
    College: "Oregon",
    Salary: 3476000,
    Stamina: 83,
    Speed: 83,
    Strength: 95,
    Injured: false,
    BelongsToTeam: "Heat",
    Playing: true
  },
  {
    FirstName: "Yao",
    LastName: "Ming",
    Position: "Center",
    Age: 24,
    Height: 7.6,
    Weight: 290,
    College: "China",
    Salary: 1560000,
    Stamina: 75,
    Speed: 75,
    Strength: 85,
    Injured: false,
    BelongsToTeam: "Heat",
    Playing: false
  },
  {
    FirstName: "Tracy",
    LastName: "McGrady",
    Position: "Shooting Guard",
    Age: 25,
    Height: 6.8,
    Weight: 235,
    College: "Alabama",
    Salary: 2850000,
    Stamina: 93,
    Speed: 92,
    Strength: 81,
    Injured: false,
    BelongsToTeam: "Heat",
    Playing: false
  },
  {
    FirstName: "Mike",
    LastName: "Bibby",
    Position: "Point Guard",
    Age: 26,
    Height: 6.1,
    Weight: 180,
    College: "Georgia",
    Salary: 2333000,
    Stamina: 88,
    Speed: 91,
    Strength: 70,
    Injured: false,
    BelongsToTeam: "Heat",
    Playing: false
  },
  {
    FirstName: "Pau",
    LastName: "Gasol",
    Position: "Power Forward",
    Age: 27,
    Height: 7.0,
    Weight: 290,
    College: "Oregon",
    Salary: 2960000,
    Stamina: 82,
    Speed: 77,
    Strength: 83,
    Injured: false,
    BelongsToTeam: "Heat",
    Playing: false
  },
  {
    FirstName: "Rick",
    LastName: "Fox",
    Position: "Small Forward",
    Age: 32,
    Height: 6.7,
    Weight: 240,
    College: "NY",
    Salary: 2387000,
    Stamina: 77,
    Speed: 75,
    Strength: 79,
    Injured: false,
    BelongsToTeam: "Heat",
    Playing: false
  },
  {
    FirstName: "Latrell",
    LastName: "Sprewell",
    Position: "Small Forward",
    Age: 27,
    Height: 6.5,
    Weight: 210,
    College: "UCLA",
    Salary: 4767000,
    Stamina: 87,
    Speed: 93,
    Strength: 91,
    Injured: false,
    BelongsToTeam: "Lakers",
    Playing: true
  },
  {
    FirstName: "Shaq",
    LastName: "O'Neil",
    Position: "Center",
    Age: 32,
    Height: 7.1,
    Weight: 330,
    College: "Arizona",
    Salary: 5345000,
    Stamina: 70,
    Speed: 75,
    Strength: 99,
    Injured: false,
    BelongsToTeam: "Lakers",
    Playing: true
  },
  {
    FirstName: "Gary",
    LastName: "Payton",
    Position: "Point Guard",
    Age: 34,
    Height: 6.3,
    Weight: 200,
    College: "Gonzaga",
    Salary: 3560000,
    Stamina: 93,
    Speed: 95,
    Strength: 75,
    Injured: false,
    BelongsToTeam: "Lakers",
    Playing: true
  },
  {
    FirstName: "Michael",
    LastName: "Jordan",
    Position: "Shooting Guard",
    Age: 34,
    Height: 6.6,
    Weight: 220,
    College: "NY",
    Salary: 6367000,
    Stamina: 97,
    Speed: 97,
    Strength: 88,
    Injured: false,
    BelongsToTeam: "Lakers",
    Playing: true
  },
  {
    FirstName: "Tim",
    LastName: "Duncan",
    Position: "Power Forward",
    Age: 33,
    Height: 7.0,
    Weight: 280,
    College: "Texas",
    Salary: 3836000,
    Stamina: 80,
    Speed: 80,
    Strength: 97,
    Injured: false,
    BelongsToTeam: "Lakers",
    Playing: true
  },
  {
    FirstName: "Ben",
    LastName: "Wallace",
    Position: "Center",
    Age: 23,
    Height: 6.11,
    Weight: 290,
    College: "Florida",
    Salary: 1836000,
    Stamina: 80,
    Speed: 80,
    Strength: 99,
    Injured: true,
    BelongsToTeam: "Lakers",
    Playing: false
  },
  {
    FirstName: "Vince",
    LastName: "Carter",
    Position: "Shooting Guard",
    Age: 25,
    Height: 6.6,
    Weight: 230,
    College: "Utah",
    Salary: 2555000,
    Stamina: 92,
    Speed: 91,
    Strength: 83,
    Injured: false,
    BelongsToTeam: "Lakers",
    Playing: false
  },
  {
    FirstName: "Antonio",
    LastName: "McDyess",
    Position: "Power Forward",
    Age: 34,
    Height: 6.9,
    Weight: 275,
    College: "Arizona",
    Salary: 4836000,
    Stamina: 75,
    Speed: 77,
    Strength: 89,
    Injured: false,
    BelongsToTeam: "Lakers",
    Playing: false
  },
  {
    FirstName: "Jason",
    LastName: "Kidd",
    Position: "Point Guard",
    Age: 31,
    Height: 6.4,
    Weight: 210,
    College: "Utah",
    Salary: 3550000,
    Stamina: 93,
    Speed: 95,
    Strength: 80,
    Injured: true,
    BelongsToTeam: "Lakers",
    Playing: false
  },
  {
    FirstName: "LeBron",
    LastName: "James",
    Position: "Small Forward",
    Age: 28,
    Height: 6.8,
    Weight: 235,
    College: "N/A",
    Salary: 6740000,
    Stamina: 95,
    Speed: 95,
    Strength: 97,
    Injured: false,
    BelongsToTeam: "Lakers",
    Playing: false
  }
];
