module.exports = [
  {
    firstname: "Marquese",
    lastname: "Chriss",
    position: "Small Forward",
    age: 22,
    height: 6.9,
    weight: 240,
    college: "Washington",
    salary: 3456000,
    stamina: 85,
    speed: 87,
    strength: 93,
    injured: false,
    team: "Warriors",
    playing: true
  },
  {
    firstname: "Willie",
    lastname: "Cauley-Stein",
    position: "Center",
    age: 26,
    height: 7.0,
    weight: 240,
    college: "Kentucky",
    salary: 5123000,
    stamina: 75,
    speed: 77,
    strength: 99,
    injured: false,
    team: "Warriors",
    playing: true
  },
  {
    firstname: "Stephen",
    lastname: "Curry",
    position: "Point Guard",
    age: 31,
    height: 6.3,
    weight: 185,
    college: "Davidson",
    salary: 4560000,
    stamina: 95,
    speed: 97,
    strength: 70,
    injured: false,
    team: "Warriors",
    playing: true
  },
  {
    firstname: "Alec",
    lastname: "Burks",
    position: "Shooting Guard",
    age: 28,
    height: 6.6,
    weight: 214,
    college: "Colorado",
    salary: 6100000,
    stamina: 96,
    speed: 96,
    strength: 87,
    injured: false,
    team: "Warriors",
    playing: true
  },
  {
    firstname: "Draymond",
    lastname: "Green",
    position: "Power Forward",
    age: 29,
    height: 6.6,
    weight: 230,
    college: "Michigan State",
    salary: 3476000,
    stamina: 83,
    speed: 83,
    strength: 95,
    injured: false,
    team: "Warriors",
    playing: true
  },
  {
    firstname: "Kevon",
    lastname: "Looney",
    position: "Center",
    age: 23,
    height: 6.9,
    weight: 222,
    college: "Oregon",
    salary: 1560000,
    stamina: 75,
    speed: 75,
    strength: 85,
    injured: false,
    team: "Warriors",
    playing: false
  },
  {
    firstname: "Klay",
    lastname: "Thompson",
    position: "Shooting Guard",
    age: 29,
    height: 6.6,
    weight: 215,
    college: "Washington State",
    salary: 2850000,
    stamina: 93,
    speed: 92,
    strength: 81,
    injured: false,
    team: "Warriors",
    playing: false
  },
  {
    firstname: "Wayne",
    lastname: "Ellington",
    position: "Point Guard",
    age: 32,
    height: 6.4,
    weight: 207,
    college: "UNC",
    salary: 2333000,
    stamina: 88,
    speed: 91,
    strength: 70,
    injured: false,
    team: "Warriors",
    playing: false
  },
  {
    firstname: "Taj",
    lastname: "Gibson",
    position: "Power Forward",
    age: 34,
    height: 6.9,
    weight: 232,
    college: "USC",
    salary: 2960000,
    stamina: 82,
    speed: 77,
    strength: 83,
    injured: false,
    team: "Warriors",
    playing: false
  },
  {
    firstname: "Damyean",
    lastname: "Dotson",
    position: "Small Forward",
    age: 25,
    height: 6.5,
    weight: 210,
    college: "Houston",
    salary: 2387000,
    stamina: 77,
    speed: 75,
    strength: 79,
    injured: false,
    team: "Warriors",
    playing: false
  },
  {
    firstname: "Troy",
    lastname: "Daniels",
    position: "Small Forward",
    age: 28,
    height: 6.4,
    weight: 205,
    college: "UCLA",
    salary: 4767000,
    stamina: 87,
    speed: 93,
    strength: 91,
    injured: false,
    team: "Lakers",
    playing: true
  },
  {
    firstname: "DeMarcus",
    lastname: "Cousins",
    position: "Center",
    age: 29,
    height: 6.11,
    weight: 270,
    college: "Kentucky",
    salary: 5345000,
    stamina: 70,
    speed: 75,
    strength: 99,
    injured: false,
    team: "Lakers",
    playing: true
  },
  {
    firstname: "Rajon",
    lastname: "Rondo",
    position: "Point Guard",
    age: 33,
    height: 6.1,
    weight: 180,
    college: "Kentucky",
    salary: 3560000,
    stamina: 93,
    speed: 95,
    strength: 75,
    injured: false,
    team: "Lakers",
    playing: true
  },
  {
    firstname: "LeBron",
    lastname: "James",
    position: "Shooting Guard",
    age: 34,
    height: 6.9,
    weight: 250,
    college: "N/A",
    salary: 6367000,
    stamina: 97,
    speed: 97,
    strength: 88,
    injured: false,
    team: "Lakers",
    playing: true
  },
  {
    firstname: "Anthony",
    lastname: "Davis",
    position: "Power Forward",
    age: 26,
    height: 6.11,
    weight: 253,
    college: "Texas",
    salary: 3836000,
    stamina: 80,
    speed: 80,
    strength: 97,
    injured: false,
    team: "Lakers",
    playing: true
  },
  {
    firstname: "Dwight",
    lastname: "Howard",
    position: "Center",
    age: 33,
    height: 6.11,
    weight: 265,
    college: "Florida",
    salary: 1836000,
    stamina: 80,
    speed: 80,
    strength: 99,
    injured: true,
    team: "Lakers",
    playing: false
  },
  {
    firstname: "Danny",
    lastname: "Green",
    position: "Shooting Guard",
    age: 32,
    height: 6.6,
    weight: 215,
    college: "North Carolina",
    salary: 2555000,
    stamina: 92,
    speed: 91,
    strength: 83,
    injured: false,
    team: "Lakers",
    playing: false
  },
  {
    firstname: "Kyle",
    lastname: "Kuzma",
    position: "Power Forward",
    age: 24,
    height: 6.8,
    weight: 221,
    college: "Utah",
    salary: 4836000,
    stamina: 75,
    speed: 77,
    strength: 89,
    injured: false,
    team: "Lakers",
    playing: false
  },
  {
    firstname: "Quinn",
    lastname: "Cook",
    position: "Point Guard",
    age: 26,
    height: 6.1,
    weight: 180,
    college: "Duke",
    salary: 3550000,
    stamina: 93,
    speed: 95,
    strength: 80,
    injured: true,
    team: "Lakers",
    playing: false
  },
  {
    firstname: "Alex",
    lastname: "Caruso",
    position: "Small Forward",
    age: 25,
    height: 6.5,
    weight: 186,
    college: "Texas",
    salary: 6740000,
    stamina: 95,
    speed: 95,
    strength: 97,
    injured: false,
    team: "Lakers",
    playing: false
  }
];
